// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace SpeakerApi.Data.Migrations
{
    [DbContext(typeof(SpeakerDbContext))]
    [Migration("20211126020852_M1")]
    partial class M1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("SpeakerLibrary.Speaker", b =>
                {
                    b.Property<string>("SpeakerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Employer")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MobileNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("Province")
                        .HasColumnType("TEXT");

                    b.Property<string>("Specialization")
                        .HasColumnType("TEXT");

                    b.HasKey("SpeakerId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            SpeakerId = "42f47adf-e619-430f-ab1c-5d002f585fba",
                            City = "Chilliwack",
                            Email = "jim@bar.ca",
                            Employer = "BC Hydro",
                            FirstName = "Jim",
                            LastName = "Bar",
                            MobileNumber = "2223334444",
                            Province = "BC",
                            Specialization = "Software engineer"
                        },
                        new
                        {
                            SpeakerId = "2f45d79a-b7ea-4579-b7b8-ad8c2f4816b1",
                            City = "Vancouver",
                            Email = "jane@amazon.ca",
                            Employer = "Amazon",
                            FirstName = "Jane",
                            LastName = "Douglas",
                            MobileNumber = "3334445555",
                            Province = "BC",
                            Specialization = "Software engineer"
                        },
                        new
                        {
                            SpeakerId = "c5ebbc74-0849-4218-901a-e666d25e2189",
                            City = "Richmond",
                            Email = "tom@ubc.ca",
                            Employer = "UBC",
                            FirstName = "Tom",
                            LastName = "Gardner",
                            MobileNumber = "4445556666",
                            Province = "BC",
                            Specialization = "Software Architecture"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
